package dk.cphbusiness.banking.backend.Selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.Test;

import static dk.cphbusiness.banking.backend.datalayer.TestDatabaseUtility.*;
import static dk.cphbusiness.banking.backend.settings.Settings.DB_NAME;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class CreateCustomerTest {
  private static WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static String dbName = DB_NAME;

  @Before
  public void setUp() throws IOException, SQLException {
    createTestDatabase();
    createTables(dbName);
    populateDatabase(dbName);

    ChromeOptions options = new ChromeOptions();
    driver = new ChromeDriver(options);
    options.addArguments("--headless", "--disable-gpu", "--window-size=1920,1200","--ignore-certificate-errors", "--silent");
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.get("http://localhost:5000/");
    driver.manage().window().setSize(new Dimension(1920, 994));

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

  }

  @After
  public void close(){
    driver.quit();
  }
  @Test
  public void createCustomer() {
    driver.get("http://localhost:5000/");
    driver.manage().window().setSize(new Dimension(976, 1010));
    driver.findElement(By.cssSelector(".svelte-149tb61 > .input_container:nth-child(1) > .svelte-n2exwy")).click();
    driver.findElement(By.cssSelector(".svelte-149tb61 > .input_container:nth-child(1) > .svelte-n2exwy")).sendKeys("Frederic Chopin");
    driver.findElement(By.cssSelector(".input-container > .input_container:nth-child(2) > .svelte-n2exwy")).click();
    driver.findElement(By.cssSelector(".input-container > .input_container:nth-child(2) > .svelte-n2exwy")).sendKeys("0123456789");
    driver.findElement(By.cssSelector(".button:nth-child(3) > .svelte-10g3g0h")).click();
    driver.findElement(By.cssSelector(".svelte-149tb61:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector(".svelte-149tb61:nth-child(2)")).getText(), is("Customer created!"));
    driver.close();
  }
}
