package dk.cphbusiness.banking.backend.Selenium;

// Generated by Selenium IDE
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static dk.cphbusiness.banking.backend.datalayer.TestDatabaseUtility.*;
import static dk.cphbusiness.banking.backend.settings.Settings.DB_NAME;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.io.IOException;
import java.sql.SQLException;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;


public class TransferTest {
    private static WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    private static String dbName = DB_NAME;



    @BeforeClass
    public static void beforeClass() throws Exception {
        createTestDatabase();
        createTables(dbName);
        populateDatabase(dbName);

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless", "--disable-gpu", "--window-size=1920,1200","--ignore-certificate-errors", "--silent");
        driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    }

    @Before
    public void setUp() {
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }

    @Test
    public void transfer() {
        //Assemble
        var amount = "90";
        driver.get("http://localhost:5000/");
        driver.manage().window().setSize(new Dimension(1920, 994));

        //Act
        driver.findElement(By.name("source")).click();
        driver.findElement(By.name("source")).sendKeys("1111111111");
        driver.findElement(By.cssSelector(".svelte-1pinpmn > .input_container:nth-child(2) > .svelte-n2exwy")).click();
        driver.findElement(By.cssSelector(".svelte-1pinpmn > .input_container:nth-child(2) > .svelte-n2exwy")).sendKeys("3333333333");
        driver.findElement(By.name("amount")).click();
        driver.findElement(By.name("amount")).sendKeys(amount);
        driver.findElement(By.cssSelector(".button:nth-child(4) > .svelte-10g3g0h")).click();
        driver.findElement(By.cssSelector("tr > .svelte-1pinpmn:nth-child(3)")).click();

        //Assert
        assertThat(driver.findElement(By.cssSelector("tr > .svelte-1pinpmn:nth-child(3)")).getText(), is("$ " + amount));
        driver.close();
    }
}
