package dk.cphbusiness.banking.backend.Selenium;// Generated by Selenium IDE
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.Test;

import static dk.cphbusiness.banking.backend.datalayer.TestDatabaseUtility.*;
import static dk.cphbusiness.banking.backend.settings.Settings.DB_NAME;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.chrome.ChromeOptions;

public class UpdateCustomerTest {
  private static WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private static String dbName = DB_NAME;

  @Before
  public void setUp() throws IOException, SQLException {
    createTestDatabase();
    createTables(dbName);
    populateDatabase(dbName);

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless", "--disable-gpu", "--window-size=1920,1200","--ignore-certificate-errors", "--silent");
    driver = new ChromeDriver(options);
    driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
    driver.get("http://localhost:5000");
    driver.manage().window().setSize(new Dimension(1920, 994));

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void close(){
    driver.quit();
  }
  @Test
  public void updateCustomer() {
    driver.get("http://localhost:5000/");
    driver.manage().window().setSize(new Dimension(976, 1010));
    driver.findElement(By.name("updatecustomer-name")).sendKeys("Frederic Chopin");
    driver.findElement(By.name("updatecustomer-cpr")).sendKeys("1234560004");
    driver.findElement(By.name("updatecustomer-submit")).click();
    assertThat(driver.findElement(By.name("updatecustomer-res")).getText(), is("Updated customer!"));
    driver.close();
  }

  @Test
  public void updateCustomerFail() {
    driver.get("http://localhost:5000/");
    driver.manage().window().setSize(new Dimension(976, 1010));
    driver.findElement(By.name("updatecustomer-name")).sendKeys("Frederic Chopin");
    driver.findElement(By.name("updatecustomer-cpr")).sendKeys("1029384756");
    driver.findElement(By.name("updatecustomer-submit")).click();
    assertThat(driver.findElement(By.name("exceptionHolder")).getText(), is("Customer does not exist"));
    driver.close();
  }
}
